---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true
  customize:
    memory: 368

provisioner:
  name: chef_zero

platforms:
- name: ubuntu-14.04
#  driver_config:
#    box: opscode-ubuntu-14.04
#    box_url: https://opscode-vm.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_provisionerless.box
#- name: ubuntu-10.04
#  driver_config:
#    box: opscode-ubuntu-10.04
#    box_url: https://opscode-vm.s3.amazonaws.com/vagrant/opscode_ubuntu-10.04_provisionerless.box

suites:
  - name: default
    run_list:
      - recipe[bacula-ng-test]
      - recipe[bacula-ng]
    attributes:
      bacula:
        fd:
          password: swordfish
        mon:
          password: swordfish
        director:
          name: "stub:director"
          password: "swordfish"
      id: "stub"
      ipaddress: "1.1.1.1"
      tags:
        - "bacula_director"
  - name: server-postgresql
    run_list:
      - recipe[bacula-ng-test]
      - recipe[bacula-ng::server]
      - recipe[bacula-ng::web]
    attributes:
      bacula:
        client:
          backup:
            - test_job
        database: postgresql
        director:
          db_password: swordfish
          password: swordfish
        fd:
          password: swordfish
        mon:
          password: swordfish
        storage:
          password: swordfish
      postgresql:
        password:
          postgres: swordfish
  - name: server-mysql
    run_list:
      - recipe[bacula-ng-test]
      - recipe[bacula-ng::server]
      - recipe[bacula-ng::web]
    attributes:
      bacula:
        database: mysql
        director:
          db_password: swordfish
          password: swordfish
        fd:
          password: swordfish
        mon:
          password: swordfish
        storage:
          password: swordfish
      mysql:
        server_debian_password: swordfish
        server_repl_password: swordfish
        server_root_password: swordfish
